CREATE TABLE gender (
ID int NOT NULL AUTO_INCREMENT,
gender varchar(45) NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE passenger (
ID INT NOT NULL AUTO_INCREMENT,
first_name VARCHAR(45) NOT NULL,
last_name VARCHAR(45) NOT NULL,
date_of_birth DATE NOT NULL,
gender_id INT NOT NULL,
email VARCHAR(45) NULL,
address VARCHAR(45) NULL,
PRIMARY KEY (ID),
FOREIGN KEY (gender_id) REFERENCES gender (ID)
);

CREATE TABLE staff (
ID INT NOT NULL AUTO_INCREMENT,
first_name VARCHAR(45) NOT NULL,
last_name VARCHAR(45) NOT NULL,
date_of_birth DATE NOT NULL,
gender_id INT NOT NULL,
title VARCHAR(45) NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (gender_id) REFERENCES gender (ID)
);

CREATE TABLE plane (
ID INT NOT NULL AUTO_INCREMENT,
manufacturer VARCHAR(45) NOT NULL,
model VARCHAR(45) NOT NULL,
seats VARCHAR(45) NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE aircrew (
ID INT NOT NULL AUTO_INCREMENT,
staff_id INT NOT NULL,
plane_id INT NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (staff_id) REFERENCES staff (ID),
FOREIGN KEY (plane_id) REFERENCES plane (ID)
);

CREATE TABLE city (
ID INT NOT NULL AUTO_INCREMENT,
name VARCHAR(45) NOT NULL,
country VARCHAR(45) NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE route (
ID INT NOT NULL AUTO_INCREMENT,
departure_city_id INT NOT NULL,
departure_date_time DATETIME NOT NULL,
arrival_city_id INT NOT NULL,
arrival_date_time DATETIME NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (departure_city_id) REFERENCES city (ID),
FOREIGN KEY (arrival_city_id) REFERENCES city (ID)
);

CREATE TABLE plane_route (
ID INT NOT NULL AUTO_INCREMENT,
plane_id INT NOT NULL,
route_id INT NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (plane_id) REFERENCES plane (ID),
FOREIGN KEY (route_id) REFERENCES route (ID)
);


CREATE TABLE payment_status (
ID INT NOT NULL AUTO_INCREMENT,
status VARCHAR(45) NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE order_status (
ID INT NOT NULL AUTO_INCREMENT,
status VARCHAR(45) NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE orders (
ID INT NOT NULL AUTO_INCREMENT,
order_status_id INT NOT NULL,
passenger_id INT NOT NULL,
plane_id INT NOT NULL,
route_id INT NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (order_status_id) REFERENCES order_status (ID),
FOREIGN KEY (passenger_id) REFERENCES passenger (ID),
FOREIGN KEY (plane_id) REFERENCES plane (ID),
FOREIGN KEY (route_id) REFERENCES route (ID)
);

CREATE TABLE payment (
ID INT NOT NULL AUTO_INCREMENT,
order_id INT NOT NULL,
payment_status_id INT NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (order_id) REFERENCES orders (ID),
FOREIGN KEY (payment_status_id) REFERENCES payment_status (ID)
);

CREATE TABLE ticket (
ID INT NOT NULL AUTO_INCREMENT,
order_id INT NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (order_id) REFERENCES orders (ID)
);